CREATE DATABASE gomokudb;

\ connect gomokudb;

CREATE USER gomokuer WITH PASSWORD 'chattchatt';

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO gomokuer;

-- I assume that each user can only appear once in match_queue
CREATE TABLE MATCH_QUEUE (
    USERID SERIAL PRIMARY KEY,
    RULEID INT NOT NULL,
    TIME TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP(0),
    MATCHED BOOLEAN NOT NULL
);

CREATE TABLE GAME_INFO (
    USERID INT NOT NULL,
    GAMEID SERIAL PRIMARY KEY,
    OPPONENTID INT NOT NULL,
    PLAYER_TURN BOOLEAN NOT NULL,
    GAME_STATUS VARCHAR(20) NOT NULL,
    PIECE_CNT INT NOT NULL
);

CREATE TABLE NEW_PIECE_INFO (
    USERID INT NOT NULL,
    GAMEID INT NOT NULL REFERENCES GAME_INFO ON DELETE CASCADE,
    X NUMERIC(7, 3) NOT NULL,
    Y NUMERIC(7, 3) NOT NULL,
    Z NUMERIC(7, 3) NOT NULL
);

CREATE TABLE ALL_PIECE_INFO (
    USERID INT NOT NULL,
    GAMEID INT NOT NULL REFERENCES GAME_INFO ON DELETE CASCADE,
    X NUMERIC(7, 3) NOT NULL,
    Y NUMERIC(7, 3) NOT NULL,
    Z NUMERIC(7, 3) NOT NULL
);