CREATE DATABASE gomokudb;

\connect gomokudb;

CREATE USER gomokuer WITH PASSWORD 'chattchatt';

-- I assume that each user can only appear once in match_queue
CREATE TABLE MATCH_QUEUE (
    USERID SERIAL PRIMARY KEY,
    RULEID INT NOT NULL,
    TIME TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP(0),
    MATCHED BOOLEAN NOT NULL
);

CREATE TABLE GAME_INFO (
    USERID INT PRIMARY KEY REFERENCES MATCH_QUEUE ON DELETE CASCADE,
    OPPONENTID INT REFERENCES MATCH_QUEUE ON DELETE CASCADE,
    RULEID INT NOT NULL,
    PLAYER_TURN BOOLEAN NOT NULL,
    GAME_STATUS VARCHAR(20) NOT NULL,
    PIECE_CNT INT NOT NULL
);

CREATE TABLE NEW_PIECE_INFO (
    USERID INT NOT NULL REFERENCES MATCH_QUEUE ON DELETE CASCADE,
    -- X NUMERIC(7, 3) NOT NULL,
    -- Y NUMERIC(7, 3) NOT NULL,
    -- Z NUMERIC(7, 3) NOT NULL
    X INT NOT NULL,
    Z INT NOT NULL
);

CREATE TABLE ALL_PIECE_INFO (
    USERID INT NOT NULL REFERENCES MATCH_QUEUE ON DELETE CASCADE,
    -- X NUMERIC(7, 3) NOT NULL,
    -- Y NUMERIC(7, 3) NOT NULL,
    -- Z NUMERIC(7, 3) NOT NULL
    X INT NOT NULL,
    Z INT NOT NULL
);

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO gomokuer;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO gomokuer;
ALTER USER gomokuer CREATEDB; -- Allow test dbs to be created
