\connect gomokudb;

INSERT INTO MATCH_QUEUE(RULEID, MATCHED)
VALUES (1, FALSE);

INSERT INTO MATCH_QUEUE(RULEID, MATCHED)
VALUES (1, FALSE);

INSERT INTO MATCH_QUEUE(RULEID, MATCHED)
VALUES (1, FALSE);

INSERT INTO GAME_INFO(USERID, OPPONENTID, PLAYER_TURN, GAME_STATUS, PIECE_CNT, RULEID)
VALUES (1, 2, FALSE, 'OnGoing', 10, 0);

INSERT INTO GAME_INFO(USERID, OPPONENTID, PLAYER_TURN, GAME_STATUS, PIECE_CNT, RULEID)
VALUES (2, 1, FALSE, 'OnGoing', 10, 0);

INSERT INTO NEW_PIECE_INFO(USERID, X, Z)
VALUES (1, 4.1234, 1.14514);

INSERT INTO NEW_PIECE_INFO(USERID, X, Z)
VALUES (2, 4, 43);

INSERT INTO ALL_PIECE_INFO (USERID, X, Z)
VALUES (1, 4.1234, 1.14514);

INSERT INTO ALL_PIECE_INFO(USERID, X, Z)
VALUES (2, 4, 43);

SELECT * FROM ALL_PIECE_INFO;